// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.SmsSender.Client.AutorestClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SmsModel
    {
        /// <summary>
        /// Initializes a new instance of the SmsModel class.
        /// </summary>
        public SmsModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SmsModel class.
        /// </summary>
        public SmsModel(string phone = default(string), string message = default(string))
        {
            Phone = phone;
            Message = message;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Phone")]
        public string Phone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Message")]
        public string Message { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Phone != null)
            {
                if (!System.Text.RegularExpressions.Regex.IsMatch(Phone, "^\\+\\d+"))
                {
                    throw new ValidationException(ValidationRules.Pattern, "Phone", "^\\+\\d+");
                }
            }
        }
    }
}
