// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.SmsSender.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SmsModel
    {
        /// <summary>
        /// Initializes a new instance of the SmsModel class.
        /// </summary>
        public SmsModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SmsModel class.
        /// </summary>
        public SmsModel(string phone = default(string), string message = default(string), string reason = default(string), string outerRequestId = default(string))
        {
            Phone = phone;
            Message = message;
            Reason = reason;
            OuterRequestId = outerRequestId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Phone")]
        public string Phone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Message")]
        public string Message { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Reason")]
        public string Reason { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OuterRequestId")]
        public string OuterRequestId { get; set; }
    }
}
